---
- hosts: all
  name: Process pgbench results
  become: false

  tasks:
    - name: Fetch pgbench data files
      ansible.builtin.fetch:
        src: "/tmp/pgbench-tps-{{ pg_version }}.csv"
        dest: "{{ results_directory }}/pgbench_data/\
              pgbench-tps-{{ pg_version }}.csv"
        flat: true
      ignore_errors: true

    - name: Generate final data points and chart
      local_action:
        chdir: "{{ results_directory }}"
        module: ansible.builtin.shell
        cmd: |
          cp {{ playbook_dir }}/post-processing {{ results_directory }}
          {{ results_directory }}/post-processing
      ignore_errors: true
