---
- hosts: primary
  name: Destroy, create, load, and reconstruct the distributed database
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Clear any previously saved system statistics data
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ ts_load }}"
        - "{{ ts_pgd_init }}"
      become: true

    - name: Remove BDR nodes
      community.postgresql.postgresql_query:
        query: >-
          SELECT bdr.part_node(node_name := '{{ item }}')
        db: "{{ pgd_cluster_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
      become: true
      become_user: "{{ pg_owner }}"
      when: inventory_hostname == 'pgd1'
      loop:
        - pgd2
        - pgd3

    - name: Cleanup replication origin
      community.postgresql.postgresql_query:
        query: >-
          SELECT pg_replication_origin_drop('bdr_local_only_origin')
        db: "{{ pgd_cluster_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
      become: true
      become_user: "{{ pg_owner }}"
      when: inventory_hostname == 'pgd1'

    - name: DROP bdr extension
      community.postgresql.postgresql_query:
        query: >-
          DROP EXTENSION bdr CASCADE
        db: "{{ pgd_cluster_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
      become: true
      become_user: "{{ pg_owner }}"
      when: inventory_hostname == 'pgd1'

    - name: "DROP {{ pgd_cluster_database }} database"
      community.postgresql.postgresql_db:
        maintenance_db: postgres
        state: absent
        name: "{{ pgd_cluster_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
        force: true
      become: true
      become_user: "{{ pg_owner }}"
      when: inventory_hostname == 'pgd1'

    - name: Restart Postgres on pgd1
      ansible.builtin.systemd:
        name: "edb-as-{{ pg_version }}"
        state: restarted
      become: true
      when: inventory_hostname == 'pgd1'

    - name: Stop Postgres on pgd2 and pgd3 [1]
      ansible.builtin.systemd:
        name: "edb-as-{{ pg_version }}"
        state: stopped
      become: true
      when: inventory_hostname in ['pgd2', 'pgd3']

    - name: Wait for port {{ pg_port }}
      ansible.builtin.wait_for:
        host: 0.0.0.0
        port: "{{ pg_port }}"
        state: started
      when: inventory_hostname == 'pgd1'

    - name: Start stats collection for load
      ansible.builtin.shell:
        cmd: ts sysstat -o {{ ts_load }}
      become: true
      async: 1
      poll: 0

    - name: Create and load the database
      ansible.builtin.command:
        cmd: >-
          dbt2 build --db-host={{ pg_login_unix_socket }}
          --db-port={{ pg_port }} --warehouses={{ dbt2_warehouse }} pgsql
          {{ pgd_cluster_database }}
      changed_when: false
      become_user: "{{ pg_owner }}"
      when: inventory_hostname == 'pgd1'

    - name: Stop system statistics collection for load
      ansible.builtin.shell:
        cmd: ts sysstat -o {{ ts_load }} -s
      become: true

    - name: Issuing CHECKPOINT on pgd1
      community.postgresql.postgresql_query:
        autocommit: true
        query: >-
          CHECKPOINT
        db: "{{ pgd_cluster_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
      become_user: "{{ pg_owner }}"
      when: inventory_hostname == 'pgd1'

    - name: Create bdr extension
      community.postgresql.postgresql_ext:
        name: bdr
        state: present
        db: "{{ pgd_cluster_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
      become: true
      become_user: "{{ pg_owner }}"
      when: inventory_hostname == 'pgd1'

    - name: Create BDR node on pgd1
      community.postgresql.postgresql_query:
        query: >-
          SELECT bdr.create_node('pgd1', 'host=pgd1 dbname={{ pgd_cluster_database }} port={{ pg_port }} user={{ pg_user }}');
        db: "{{ pgd_cluster_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
      become: true
      become_user: "{{ pg_owner }}"
      when: inventory_hostname == 'pgd1'

    - name: Create BDR group on pgd1
      community.postgresql.postgresql_query:
        query: >-
          SELECT bdr.create_node_group('pgddb_group');
        db: "{{ pgd_cluster_database }}"
        login_user: "{{ pg_user }}"
        port: "{{ pg_port }}"
        login_unix_socket: "{{ pg_login_unix_socket }}"
      become: true
      become_user: "{{ pg_owner }}"
      when: inventory_hostname == 'pgd1'

    - name: Cleaning up Postgres file systems
      ansible.builtin.shell: |
        rm -rf {{ pg_data }}
        rm -rf {{ pg_wal }}
        mkdir {{ pg_wal }}
        chown enterprisedb.enterprisedb {{ pg_wal }}
        # Required by bdr_init_physical
        chown enterprisedb.enterprisedb {{ pg_data | dirname }}
      become: true
      when: inventory_hostname in ['pgd2', 'pgd3']

    - name: Start stats collection for PGD initialization
      ansible.builtin.shell:
        cmd: ts sysstat -o {{ ts_pgd_init }}
      become: true
      async: 1
      poll: 0

    - name: Building pgd2 and pgd3 with bdr_init_physical
      ansible.builtin.shell: |
        /usr/edb/as{{ pg_version }}/bin/bdr_init_physical -D {{ pg_data }} \
                -l /tmp/bdr_init_physical.log \
                -n {{ inventory_hostname }} \
                --node-group-name pgddb_group \
                -d 'host=pgd1 port={{ pg_port }} dbname={{ pgd_cluster_database }} user={{ pgd_replication_user }}' \
                --local-dsn 'host={{ inventory_hostname }} port={{ pg_port }} dbname={{ pgd_cluster_database }} user={{ pg_user }}'
      when: inventory_hostname in ['pgd2', 'pgd3']
      become_user: "{{ pg_owner }}"

    - name: Stop system statistics collection for PGD initialization
      ansible.builtin.shell:
        cmd: ts sysstat -o {{ ts_pgd_init }} -s
      become: true

    # Need to use pg_ctl here instead of operating system service because
    # bdr_init_physical starts the database.
    - name: Stop Postgres on pgd2 and pgd3 [2]
      ansible.builtin.shell: |
        /usr/edb/as{{ pg_version }}/bin/pg_ctl -D {{ pg_data }} stop
      when: inventory_hostname in ['pgd2', 'pgd3']
      become_user: "{{ pg_owner }}"

    - name: Updating PGWAL location
      ansible.builtin.shell: |
        rm -rf {{ pg_wal }}/*
        rsync -cavr {{ pg_data }}/pg_wal/* {{ pg_wal }}/.
        rm -rf {{ pg_data }}/pg_wal/
        ln -s {{ pg_wal }} {{ pg_data }}/pg_wal
      become: true
      when: inventory_hostname in ['pgd2', 'pgd3']

    - name: Starting Postgres on pgd2 and pgd3
      ansible.builtin.systemd:
        name: "edb-as-{{ pg_version }}"
        state: started
      become: true
      when: inventory_hostname in ['pgd2', 'pgd3']

    - name: Process pidstat data
      ansible.builtin.shell:
        cmd: ts process-pidstat -i {{ item }}/pidstat.txt
      loop:
        - "{{ ts_load }}"
        - "{{ ts_pgd_init }}"
      become: true

    - name: Plot sar data
      ansible.builtin.shell:
        cmd: ts plot-sar -i {{ item }}/sar
      loop:
        - "{{ ts_load }}"
        - "{{ ts_pgd_init }}"
      become: true

    - name: Plot pidstat data
      ansible.builtin.shell:
        cmd: ts plot-pidstat -i {{ item }}/pidstat.csv -o {{ item }}/pidstat
      loop:
        - "{{ ts_load }}"
        - "{{ ts_pgd_init }}"
      become: true

    - name: Fetch system statistics
      ansible.posix.synchronize:
        mode: pull
        src: "{{ item }}"
        dest: "{{ results_directory }}/{{ inventory_hostname }}/"
      loop:
        - "{{ ts_load }}"
        - "{{ ts_pgd_init }}"
      become: true
